### ISSUE TITLE
"matrix" style monitoring

### ISSUE THREAD

**Issue by mmastrac** [mmastrac/stylus#3]
A `matrix` should allow you to configure a single file that can use multiple axes to simplify configuration.

For example:

```
matrix:
  - axis: [1,2,3]
  - variable: index
  - config:
      id: raspberry-pi-{{index}}
      timeout: 30s
      interval: 60s
      command: test.sh
```
